services:
  Savosik\OzonBundle\Command\OzonCategoriesUpdateCommand:
    public: true
    tags:
      - { name: 'console.command', command: 'ozon:categories:update' }

  Savosik\OzonBundle\Service\:
    resource: '../../Service/*'